version: '3.8'
services:

  nginx: 
    image: nginx:latest
    container_name: cinemas-nginx
    volumes:
      - ./backend:/var/www/backend
      - ./frontend:/var/www/app
      - ./backend/.docker/nginx/conf.d:/etc/nginx/conf.d
    ports: 
      - 8080:80
    depends_on:
      - backend
      - app

  backend:
    build:
      context: ./backend/.docker
      dockerfile: Dockerfile
    volumes:
      - ./backend:/var/www/backend
    container_name: cinemas-backend
    depends_on:
      - db

  db: 
    image: mysql:8.0
    restart: always
    volumes:
      - ./tmp/db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: cinemas
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3366:3306
    container_name: cinemas-db

  app:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: cinemas-app
    working_dir: /var/www/app
    volumes:
      - ./frontend:/var/www/app